### ISSUE TITLE
How do I connect the server to League Observer tool?

### ISSUE THREAD

**Issue by AlmondJam** [RCVolus/league-prod-toolkit#110]
#After completing the installation process, including the authentication process, running start.bat was able to enter http://localhost:3003/. All modules will glow green and experiment with 9 bots and my account as a private tournament. Almost everything seems to have been successful, but the Observer tool notifies you that you have not reached the server. What should we do now?

I authenticated with the KR server, and the database account created a new admin account with root privileges and logged in.

here it is the screenshot of tools, script history of start.bat, and toolkit module page, etc.
![image](https://user-images.githubusercontent.com/105035979/167110516-4ef4aaf7-d782-4c7f-86d3-10fc717d01ad.png)

![image](https://user-images.githubusercontent.com/105035979/167110686-e79b8c76-8b31-4870-aa2b-9fe4b34c6696.png)

![image](https://user-images.githubusercontent.com/105035979/167110779-fd42a63f-8738-481a-adf1-bd3044a15ee4.png)

![image](https://user-images.githubusercontent.com/105035979/167110902-196b2e6b-ebe9-4854-a8c3-4cde63c4863b.png)

+sorry bout broken English. thank you.

**Comment by AlmondJam** [comment]
++ and i think some theme files also didnt downloaded :/ 
I remember reading a script that didn't seem to have downloaded the theme file during the installation process.
![image](https://user-images.githubusercontent.com/105035979/167113718-be5326c6-0f85-4c2b-a694-99f5d0e26a5e.png)

**Comment by sdomi4** [comment]
It looks like authentication is enabled, but no key is configured in the observer tool. You can configure a key by opening the observer tool settings (File -> Open Settings) and configuring the "server-api-key" value. Make sure to restart the observer tool after updating the settings.

There was an issue with the default theme download in version 1.0.1 which is fixed in v1.1.0. You can either reinstall or grab the theme manually [here](https://github.com/rcv-prod-toolkit/theme-default/releases/tag/v1.1.0). Then all you need to do is extract the default theme folder to the theming module (the folder structure should be `...\prod-toolkit\modules\plugin-theming\themes\theme-default`. The theme should then be available in the toolkit after restarting or reloading themes.

**Comment by AlmondJam** [comment]
> It looks like authentication is enabled, but no key is configured in the observer tool. You can configure a key by opening the observer tool settings (File -> Open Settings) and configuring the "server-api-key" value. Make sure to restart the observer tool after updating the settings.
> 
> There was an issue with the default theme download in version 1.0.1 which is fixed in v1.1.0. You can either reinstall or grab the theme manually [here](https://github.com/rcv-prod-toolkit/theme-default/releases/tag/v1.1.0). Then all you need to do is extract the default theme folder to the theming module (the folder structure should be `...\prod-toolkit\modules\plugin-theming\themes\theme-default`. The theme should then be available in the toolkit after restarting or reloading themes.

thank you so muchh!!! I could launch the tools successfully and find the in-game overlay!!

but the positions of overlay are gone wrong.... even resetting the size of interfaces it still can't settle the problem😥 how to customize the position of overlay? is that included in theme.json or smth?

and I wonder how to apply Riot API key only during "install.bat" too. (key that starts to RGAPI- ~~~, not RCVPT) I can't complete Runes, end of game overlay.

Thanks for helping the problems and making such a wonderful tool!

**Comment by sdomi4** [comment]
The overlay positions should all work by default (even without a theme). The most frequent cause of this being misaligned is the default CSS in OBS browser sources, deleting this usually resolves this.

The Riot API key is an actual key from the Riot API (obtained at developer.riotgames.com), which is still configured locally since we have not yet obtained a production key for this.

**Comment by AlmondJam** [comment]
> The Riot API key is an actual key from the Riot API (obtained at developer.riotgames.com), which is still configured locally since we have not yet obtained a production key for this.

I deleted CSS script and it worked! Thanks!!

But "obtain a production key for this" mean we cant activate these options now?

If its not, Simply I want to know how to activate these options. Is there a way to activate the Riot API key separately? Do I have to run it separately on API key tab in localhost:3003/?

**Comment by sdomi4** [comment]
For now, you can only get the features relying on the Riot API to work by configuring a valid API key locally. For testing purposes, you can use a development key. To configure this after installation, you can just set the key in `"...\prod-toolkit\modules\plugin-config\config.json"`.

This no longer be necessary in the future once our application for a production key goes through :)

**Comment by AlmondJam** [comment]
Thanks! I think I can use it perfectly if I solve a few parts now!

a. Even if I change the Riot API according to the method you told me, the Runes, end of game overlay is still not working (I think), so I want to connect the game state module manually, where can I check the game id?
b. I heard that you can add a nickname to the game state inquiry method, but is it possible to use a Korean nickname? (I don't understand this function in itself)
c. Do I have to stay in the LoL client's result window after watching the end of game overlay?
d. I'd like to proceed with the tournament in the private room, so can I use all the Runes, end of game? If not, I wonder if I should use a tournament hosting tool like Battlefy separately.

I'm sorry I kept asking. That's how attractive the toolkit you made is, and I want to tell my friends around me!
I introduced the iname function to the tournament participants, and everyone is going crazy!
Thank you for always letting me know. 😭😭

**Comment by AlmondJam** [comment]
> Thanks! I think I can use it perfectly if I solve a few parts now!
> 
> a. Even if I change the Riot API according to the method you told me, the Runes, end of game overlay is not working (I think), so I want to connect the game state module manually, where can I check the game id? b. I heard that you can add a nickname to the game state inquiry method, but is it possible to use a Korean nickname? (I don't understand this function in itself) c. Do I have to stay in the LoL client's result window after watching the end of game overlay? d. I'd like to proceed with the tournament in the private room, so can I use all the Runes, end of game? If not, I wonder if I should use a tournament hosting tool like Battlefy separately.
> 
> I'm sorry I kept asking. That's how attractive the toolkit you made is, and I want to tell my friends around me! I introduced the iname function to the tournament participants, and everyone is going crazy! Thank you for always letting me know. 😭😭

I can't use the computer right now, so there may be some mistakes. Problem A did not show any overlay from the browser source as if it was not connected at all. I will attach a screenshot if you need it later. Thank you.

**Comment by sdomi4** [comment]
No worries, always glad to help out and answer any questions :)
As to the questions:
a) If the observer tool is connected and spectating the game, the game ID should load automatically. If the game is live, you can look up the game ID using the summoner search in the game state module. If the game is already over, you can find gameIDs on external sites (leagueofgraphs.com works well for this).

b) You can look up live games for any summoner by entering the name in the Game State module, this should work for Korean names (although we never tried...). This loads the runes; the matchID is also output in the console.

c) No, postgame stats are independent from the client, they are obtained through the matchv5 API.

d) The API features (Runes, postgame stats) rely on the game being available in the spectatorv4 API and the matchv5 API. By default, custom games are not contained in the matchv5 API, which is why postgame stats don't work there. Using tournament codes is the only way around this, we use Battlefy to do this for our own tournaments (but any tournament tool using tournament codes will work).

**Comment by AlmondJam** [comment]
Thank you!! Maybe it didn't work because I tested it in a customized game. I'm glad Battlefy is easy to handle. Now I think I can handle this.

Finally, I would like to change the logo and overlay, using the setting fonts, custom logos/overlays method that the wiki told me about, theme.json, index.scss - and put the new logo image file in the folder "...\modules\themeing\your_theme\"" (which I created because it didn't exist), but the console failed to find the module?

In Custom Logos/Overlays, are json, scss, and image files not all that need to be saved?
I will attach some screenshots as well.

1) console error message.
![image](https://user-images.githubusercontent.com/105035979/168572986-58cf83a2-9c5e-485f-8f07-9f6694700d56.png)

2) script of ...\modules\themeing\your_theme\index.scss

> :root {
  --blue-team: #029EF7;
  --blue-team-dark: hsl(202, 98%, 40%);
  --red-team: #FF5A64;
  --red-team-dark: hsl(356, 100%, 59%);
  --accent-color: #61e15c;
  --text-color: #eeeeee;
  --background-color: #0d0d0d;
  --primary-font-family: "D2Coding", monospace;
  --secondary-font-family: sans-serif;
  --logo-path: url(/pages/op-themeing/active/logo.png);
}

themes.json is same as a default setting but the name has changed to BCK Theme. (tournament name like LCK😐)

aaaaaand 
![image](https://user-images.githubusercontent.com/105035979/168574247-e4119e0b-84e4-4ae2-a0cd-92a5b18b1cf1.png)

screenshot of file explorer (I think it's useless :/)

thanks for the help always!

**Comment by sdomi4** [comment]
I'm not sure if this is the only thing causing an issue here, but renaming `themes.json` to `theme.json` should already help :)

If the same error message still occurs, you can try renaming the folder from `your_theme` (this is just a placeholder in the wiki) to `theme-BCK`.

**Comment by AlmondJam** [comment]
> I'm not sure if this is the only thing causing an issue here, but renaming `themes.json` to `theme.json` should already help :)
> 
> If the same error message still occurs, you can try renaming the folder from `your_theme` (this is just a placeholder in the wiki) to `theme-BCK`.

![image](https://user-images.githubusercontent.com/105035979/169686790-70869771-cbf2-422f-a149-820b29ceafa3.png)

Thank you so much!!! We just had a tournament for two days, and thanks to you, we were able to get great quality of the tournament!!!

I recorded it, and I'm uploading it on YouTube! I'm so excited to enjoy this competition with my friends😎😎😎

I was so satisfied that I wanted to use it whenever a new function came out! Keep making good tools! I'll always support you.❤❤❤❤❤

**Comment by Himyu** [comment]
First of all thank you for the amazing feedback and we are happy that you like what we are doing.

Second of all would you mind providing us with the lil to the youtube video? If it's public ofc ;)

**Comment by AlmondJam** [comment]
> First of all thank you for the amazing feedback and we are happy that you like what we are doing.
> 
> Second of all would you mind providing us with the lil to the youtube video? If it's public ofc ;)

I just voted among the participants, and they all turned out to be okay!

https://www.youtube.com/watch?v=WV1aqp_a_V0

This is the link to the final recording that was the best hosting!

The modules I used are in-game, team panel, champion-select!

I was going to try Battlefy, but I couldn't apply it because it was already too late😥 But everyone liked it.
I made all the other graphics besides the module by myself. 

I don't know because it's Korean, but the nickname of the NMD team's top liner is a **little** weird. Please don't listen to it too loudly.🥵🥵

https://youtube.com/playlist?list=PLRwy-YM5h-EP9xbDIB5Yv8mi1zdDbxO6_

This is the video of the previous competition using lol-pick-ban-ui that you made before, and the entire playlist that includes the preliminary rounds of this competition. (Please ignore Overwatch thing. It's a playlist of the entire competition I made.)

Once again, thank you so much for helping me hold this competition. I won't be able to do it soon because of college entrance exams, but so many people like it that I'm going to have a competition someday. So please keep making good toolkits! I'll be rooting for you guys!🥰🥰🥰
