### ISSUE TITLE
New features are not working

### ISSUE THREAD

**Issue by shir0xyz** [RCVolus/league-prod-toolkit#146]
Custom killfeed, objective kills and platings are not working as of 27.10.2022. I didn't get any erros while kills happened. Observer tool is synced up with every option. Inhibitors are not working as well.

**Comment by Himyu** [comment]
did you also sync all the ingame modules in your observer tool (attach a screenshot if possible) and can you please confirm that you have set the config in the ingame module correctly (attache screenshot as well)?

**Comment by shir0xyz** [comment]
![cfgsc](https://user-images.githubusercontent.com/48430352/198151376-b6098ffb-a1c0-4652-ae7e-a67b99afba6d.png)
![ot1](https://user-images.githubusercontent.com/48430352/198151386-a9ca0176-b506-424c-994e-056215311c97.png)
![ot2](https://user-images.githubusercontent.com/48430352/198151608-4862a3db-4e6b-41dc-a2d2-05e0700d4308.png)

**Comment by shir0xyz** [comment]
Update: we've reinstalled observer tool, toolkit server and kills started to work. We're waiting on events for platings and objectives.

**Comment by Himyu** [comment]
Can you please also provide a screenshot of your ingame module config? Should look something like this 
![image](https://user-images.githubusercontent.com/63208379/198152037-383413db-3556-45a9-9afb-7210f3c703f0.png)

**Comment by shir0xyz** [comment]
![image](https://user-images.githubusercontent.com/48430352/198152130-606e1529-82c1-48e8-969c-1c0bf99b1e50.png)

**Comment by Himyu** [comment]
Ok perfect! Did you add a LiveEvents.ini file to your LoL Config folder?
if not please do so and add the following content to it:

```ini
OnKillDragon_Spectator
OnKillRiftHerald_Spectator
OnKillWorm_Spectator
OnTurretPlateDestroyed
OnDragonSoulGiven
```

**Comment by shir0xyz** [comment]
We have first three values, we'll add those 2 last. Would it work mid-game?

**Comment by Himyu** [comment]
no, unfortunately it will not you would have to restart the game for changes to take effect

**Comment by shir0xyz** [comment]
Alright thanks, I'll let you know how it works when we'll head to next game.

**Comment by Himyu** [comment]
Ok thank you for the feedback so far and good luck for the next one

**Comment by shir0xyz** [comment]
We have killfeed and inhibitors, but objectives and platings are still not working.

**Comment by Himyu** [comment]
After changing your config did you also close your League client completely? Because League only includes changes to the config and the Config folder when the client is started.

**Comment by shir0xyz** [comment]
Yes, we restarted a couple of times

**Comment by Himyu** [comment]
If you could try it ones more because some times it does not work on the first go?

**Comment by shir0xyz** [comment]
Another week and another not working plates. As of new features, delay is not working, nameplates and baron power-play are working.
Update: drake and baron are working as expected, no idea why only after reset. Probably the problem is us watching some replays in between.

**Comment by shir0xyz** [comment]
New observation, backend server is crashing when the game ends. I'll provide the screenshot later.

**Comment by Himyu** [comment]
do you have all the newest patch for the plugins, I know this issue but there should be a fix for it. But I wait for your screenshot to know more

**Comment by shir0xyz** [comment]
Backend server was updated by me today few hours ago, so it all should be up to date

**Comment by Himyu** [comment]
i don't mean the server itself i rather mean the plugins and modules

**Comment by shir0xyz** [comment]
Just confirmed, platings are working. My only concern now are delay and those crashes at the end of the game

**Comment by shir0xyz** [comment]
Just got a random crash mid-game.
![image](https://user-images.githubusercontent.com/48430352/199617709-f344eca7-f4de-47dc-9663-73def2d3f977.png)

**Comment by Himyu** [comment]
can you give me a screenshot of your module page (http://localhost:3003/modules) when the toolkit is open

**Comment by shir0xyz** [comment]
![image](https://user-images.githubusercontent.com/48430352/199623635-2bb720ef-fbed-4135-b0c5-dd38ddaaca92.png)

**Comment by shir0xyz** [comment]
Also on side note, I could use some instructions for Twitch module

**Comment by Himyu** [comment]
Instruction for the twitch module will be added to the wiki shortly.
And for your crash, there will be fix by tomorrow as well.

**Comment by shir0xyz** [comment]
Awesome, any chances for update in terms of delay thing?

**Comment by Himyu** [comment]
What exactly is not working when using the delay?

**Comment by shir0xyz** [comment]
Well it's not delaying the ingame overlays

**Comment by Himyu** [comment]
ok i will have a look at that tomorrow as well

**Comment by shir0xyz** [comment]
Thank you very much

**Comment by Himyu** [comment]
How much delay did you set to test it?

**Comment by shir0xyz** [comment]
3, I guess it's measured by seconds

**Comment by Himyu** [comment]
Ok pls try it with 3000 since its measured I'm milliseconds 
I will ad so note to the ui for that

**Comment by shir0xyz** [comment]
And now delay is working

**Comment by Himyu** [comment]
Another question, your crash after the game, was that for a customer game or a normal game?

**Comment by shir0xyz** [comment]
It's all during custom games

**Comment by shir0xyz** [comment]
It seems like delay is messing with timer of baron power-play

**Comment by Himyu** [comment]
messing in wich way?

**Comment by Himyu** [comment]
and the crash has been fixed with the latest patch of module league state https://github.com/rcv-prod-toolkit/module-league-state/releases/tag/v4.8.1

**Comment by shir0xyz** [comment]
> messing in wich way?

It shows 00:00 instead of countdown

**Comment by Himyu** [comment]
Ok, I had this issue during development face but fixed it before making it public. If you try downloading the newest version of the in-game module it might fix the issue 
If not, I will have a new look at it.

**Comment by shir0xyz** [comment]
Updating game state and ingame modules didn't fix power-play timer

**Comment by shir0xyz** [comment]
And yes, the server is not crashing but it's reloading everything

**Comment by shir0xyz** [comment]
Another crash just popped up
![image](https://user-images.githubusercontent.com/48430352/199633759-2819b181-8dee-4881-838c-f2c9698f1aac.png)

**Comment by shir0xyz** [comment]
Something must have broke and I lost all player names from draft overlay

**Comment by Himyu** [comment]
> And yes, the server is not crashing but it's reloading everything

what do you mean by reloading everything?

**Comment by shir0xyz** [comment]
It acts like it crashed but cmd windows stays untouched

**Comment by Himyu** [comment]
ah, I saw today what you mean I will try to find a solution for that.
For the delay, breaking the power play timer, I added a patch today.

**Comment by Himyu** [comment]
I also added a path to the module league static to fix the in-game reset. If you try it out let me know how it went.
